/**
 * Y3 — the web app's copy of which permission each API route requires:
 * apps/web/src/lib/route-permissions.gen.ts, written from the routes the app
 * registers (lib/route-registry.ts) by `pnpm --filter api gen:route-permissions`.
 * routes/route-permissions.integration.test.ts fails when the copy is stale.
 */
import type { RegisteredRoute } from './route-registry.js'

/** From apps/api. */
export const WEB_ROUTE_TABLE = '../web/src/lib/route-permissions.gen.ts'

const PREFIX = '/api/v1'

export function routePermissionsSource(routes: RegisteredRoute[]): string {
  const rows = new Map<string, string>()
  for (const { method, url, permission } of routes) {
    if (!url.startsWith(`${PREFIX}/`)) continue
    rows.set(`${method} ${url.slice(PREFIX.length)}`, permission ? `{ action: '${permission.action}', resource: '${permission.resource}' }` : 'null')
  }
  const lines = [...rows].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)).map(([key, value]) => `  '${key}': ${value},`)
  return [
    '// Generated by `pnpm --filter api gen:route-permissions` from the API\'s routes. Do not edit.',
    '// Every route under /api/v1, and the permission its requirePermission check needs (null: none).',
    '',
    'export const ROUTE_PERMISSIONS: Record<string, { action: string; resource: string } | null> = {',
    ...lines,
    '}',
    '',
  ].join('\n')
}
